name: PR Environment
on:
  pull_request:
    branches:
      - 'master'
    types: [closed]

jobs:
  close:
    name: Close
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Print
        run: echo "Removing pull request environment"
